name: Deploy to EC2

on:
  push:
    paths-ignore:
      - '.github/workflows/**'
    branches:
      - main
      - response_time_escenario
    
  pull_request:
    paths-ignore:
      - '.github/workflows/**'
    branches:
      - main
      - response_time_escenario

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -l ec2-user ${{ secrets.EC2_HOST }} <<-EOF
          cd /home/ec2-user/CreateEvent-NodeJS
          git pull
          sudo systemctl restart create-event.service
        EOF